description: |
  Push the files to github
parameters:
  bot-name:
    default: circleci-bot
    description: |
      User name to commit
    type: string
  bot-email:
    default: circleci@bot-noreply.com
    description: |
      Email to commit
    type: string

steps:
  - run:
      name: Config user git
      command: |
        # Config git
        git config credential.helper 'cache --timeout=120'
        git config user.name "<<parameters.bot-name>>"
        git config user.email "<<parameters.bot-email>>"
